### ISSUE TITLE
"tcp_connection_is_cellular No connected path" when sending to TCP client

### ISSUE THREAD

**Issue by arlomedia** [sammysmallman/OSCKit#27]
I've set up code very similar to the sample code from the ReadMe:

```
func sendData() {
	let client = OSCTcpClient(host: "10.0.1.24", port: UInt16(24601), streamFraming: .SLIP, delegate: self)
	let data: [OSCArgumentProtocol] = ["a", "b", "c"]
	do {
		let message = try OSCMessage(with: "/my/app/method", arguments: data)
		try client.send(.message(message))
	} catch {
		print("error sending message") // not called
	}
}

func client(_ client: OSCTcpClient, didConnectTo host: String, port: UInt16) {
	print("Client did connect to \(host):\(port)") // called
}

func client(_ client: OSCTcpClient, didSendPacket packet: OSCPacket) {
	print("Client did send packet") // not called
}
```

When I run this, my "error sending message" is not called and "client did connect" is called, but "client did send" is not called and these messages appear in the console log:

```
Client did connect to 10.0.1.24:24601
[connection] nw_connection_copy_connected_path [C9] Client called nw_connection_copy_connected_path on unconnected nw_connection
[] tcp_connection_is_cellular No connected path
```

It looks like that's from one of the dependencies, but web searches have turned up very little on those messages. Can you give any insight on this?

I just added OSCKit and its dependencies last week, so I have very recent if not the current versions. I'm running this on iPads with iOS 15 and iOS 18 and both are wi-fi only, so I don't know where the message about a cellular connection is coming from.

For testing, I'm sending to the OSCSmith app on a Mac, which I can switch between UDP and TCP. Connecting and sending messages from OSCUdpClient works fine. With OSCTcpClient, OSCSmith shows the connection but no incoming messages. This matches what I see within my app on the iPads.

**Comment by arlomedia** [comment]
I see the problem now. The first two lines of the OSCTcpClient.send() function are:

```
try connect()
guard isConnected else { return }
```

This is returning because apparently the connect() function takes some time and runs asynchronously. If I create the client, then call its connect() function, then wait for didConnectTo() before sending a message, it works.

If that's the intended behavior, I would recommend updating the Quick Start code in the README.

If it's not the intended behavior, then perhaps the send() function could be updated to call connect() if needed, then call itself again after the connection is completed.

**Comment by sammysmallman** [comment]
That is the intended behaviour. I'll update the documentation. Thanks for pointing that out.
