### ISSUE TITLE
Build errors: The package product 'CocoaAsyncSocket' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0

### ISSUE THREAD

**Issue by JCurtisRMIT** [sammysmallman/OSCKit#30]
`The package product 'CocoaAsyncSocket' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0`

[SO](https://stackoverflow.com/questions/64309926/how-to-set-minimum-supported-ios-version) Suggestion:

```
You have to add the platforms section to your Package.swift file like line below:

let package = Package(
    name: "YOUR_PACKAGE_NAME",
    platforms: [
        .iOS(.v12),
        .tvOS(.v12),
        .watchOS(.v5),
        .macOS(.v10_15)
    ],

```

My build target is iOS 11. So seems that the package itself needs the minimum target set as above. Local copy seems to be locked for editing when using XCode's package manager.

**Comment by sammysmallman** [comment]
Cheers @JCurtisRMIT that should be fixed for you now.
