### ISSUE TITLE
FR: Client Example demonstrating correct use of TimeTags 

### ISSUE THREAD

**Issue by JCurtisRMIT** [sammysmallman/OSCKit#35]
It would be helpful to see how to correctly implement timetags and sync in bundles

**Comment by sammysmallman** [comment]
Hey @JCurtisRMIT, I agree. I'd like to do a lot more with Bundles, including adding them to OSCAnnotations. Let me see what I can come up with.

**Comment by sammysmallman** [comment]
Hey @JCurtisRMIT with the big rework for OSCKit 3.0 I'll be rolling all core OSC logic including timetags into [CoreOSC](https://github.com/sammysmallman/CoreOSC). I haven't got round to writing up a demonstration of what you're after, but when I do it'll be in there.
